import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { ClerkProvider } from '@clerk/nextjs'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500`}>
      <ClerkProvider>{children} </ClerkProvider></body>
    </html>
    
  );
}
